# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/david/shared/Projects/HexWorld

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/david/shared/Projects/HexWorld

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/david/shared/Projects/HexWorld && $(CMAKE_COMMAND) -E cmake_progress_start /home/david/shared/Projects/HexWorld/CMakeFiles /home/david/shared/Projects/HexWorld/engine//CMakeFiles/progress.marks
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/david/shared/Projects/HexWorld/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/david/shared/Projects/HexWorld && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
engine/CMakeFiles/engine.dir/rule:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 engine/CMakeFiles/engine.dir/rule
.PHONY : engine/CMakeFiles/engine.dir/rule

# Convenience name for target.
engine: engine/CMakeFiles/engine.dir/rule
.PHONY : engine

# fast build rule for target.
engine/fast:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/build
.PHONY : engine/fast

# target to build an object file
src/camera.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/camera.o
.PHONY : src/camera.o

# target to preprocess a source file
src/camera.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/camera.i
.PHONY : src/camera.i

# target to generate assembly for a file
src/camera.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/camera.s
.PHONY : src/camera.s

# target to build an object file
src/debug.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/debug.o
.PHONY : src/debug.o

# target to preprocess a source file
src/debug.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/debug.i
.PHONY : src/debug.i

# target to generate assembly for a file
src/debug.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/debug.s
.PHONY : src/debug.s

# target to build an object file
src/directory.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/directory.o
.PHONY : src/directory.o

# target to preprocess a source file
src/directory.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/directory.i
.PHONY : src/directory.i

# target to generate assembly for a file
src/directory.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/directory.s
.PHONY : src/directory.s

# target to build an object file
src/engine.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/engine.o
.PHONY : src/engine.o

# target to preprocess a source file
src/engine.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/engine.i
.PHONY : src/engine.i

# target to generate assembly for a file
src/engine.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/engine.s
.PHONY : src/engine.s

# target to build an object file
src/engine_component.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/engine_component.o
.PHONY : src/engine_component.o

# target to preprocess a source file
src/engine_component.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/engine_component.i
.PHONY : src/engine_component.i

# target to generate assembly for a file
src/engine_component.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/engine_component.s
.PHONY : src/engine_component.s

# target to build an object file
src/framebuffer.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/framebuffer.o
.PHONY : src/framebuffer.o

# target to preprocess a source file
src/framebuffer.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/framebuffer.i
.PHONY : src/framebuffer.i

# target to generate assembly for a file
src/framebuffer.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/framebuffer.s
.PHONY : src/framebuffer.s

# target to build an object file
src/gui/debug/gui_debug.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/debug/gui_debug.o
.PHONY : src/gui/debug/gui_debug.o

# target to preprocess a source file
src/gui/debug/gui_debug.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/debug/gui_debug.i
.PHONY : src/gui/debug/gui_debug.i

# target to generate assembly for a file
src/gui/debug/gui_debug.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/debug/gui_debug.s
.PHONY : src/gui/debug/gui_debug.s

# target to build an object file
src/gui/fonts.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/fonts.o
.PHONY : src/gui/fonts.o

# target to preprocess a source file
src/gui/fonts.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/fonts.i
.PHONY : src/gui/fonts.i

# target to generate assembly for a file
src/gui/fonts.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/fonts.s
.PHONY : src/gui/fonts.s

# target to build an object file
src/gui/gui.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/gui.o
.PHONY : src/gui/gui.o

# target to preprocess a source file
src/gui/gui.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/gui.i
.PHONY : src/gui/gui.i

# target to generate assembly for a file
src/gui/gui.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/gui.s
.PHONY : src/gui/gui.s

# target to build an object file
src/gui/gui_ext.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/gui_ext.o
.PHONY : src/gui/gui_ext.o

# target to preprocess a source file
src/gui/gui_ext.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/gui_ext.i
.PHONY : src/gui/gui_ext.i

# target to generate assembly for a file
src/gui/gui_ext.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/gui/gui_ext.s
.PHONY : src/gui/gui_ext.s

# target to build an object file
src/io/inotify/inotify_context.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/inotify/inotify_context.o
.PHONY : src/io/inotify/inotify_context.o

# target to preprocess a source file
src/io/inotify/inotify_context.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/inotify/inotify_context.i
.PHONY : src/io/inotify/inotify_context.i

# target to generate assembly for a file
src/io/inotify/inotify_context.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/inotify/inotify_context.s
.PHONY : src/io/inotify/inotify_context.s

# target to build an object file
src/io/inotify/inotify_handler.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/inotify/inotify_handler.o
.PHONY : src/io/inotify/inotify_handler.o

# target to preprocess a source file
src/io/inotify/inotify_handler.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/inotify/inotify_handler.i
.PHONY : src/io/inotify/inotify_handler.i

# target to generate assembly for a file
src/io/inotify/inotify_handler.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/inotify/inotify_handler.s
.PHONY : src/io/inotify/inotify_handler.s

# target to build an object file
src/io/io.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/io.o
.PHONY : src/io/io.o

# target to preprocess a source file
src/io/io.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/io.i
.PHONY : src/io/io.i

# target to generate assembly for a file
src/io/io.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/io.s
.PHONY : src/io/io.s

# target to build an object file
src/io/resource.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/resource.o
.PHONY : src/io/resource.o

# target to preprocess a source file
src/io/resource.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/resource.i
.PHONY : src/io/resource.i

# target to generate assembly for a file
src/io/resource.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/io/resource.s
.PHONY : src/io/resource.s

# target to build an object file
src/light.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/light.o
.PHONY : src/light.o

# target to preprocess a source file
src/light.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/light.i
.PHONY : src/light.i

# target to generate assembly for a file
src/light.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/light.s
.PHONY : src/light.s

# target to build an object file
src/load_shader.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/load_shader.o
.PHONY : src/load_shader.o

# target to preprocess a source file
src/load_shader.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/load_shader.i
.PHONY : src/load_shader.i

# target to generate assembly for a file
src/load_shader.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/load_shader.s
.PHONY : src/load_shader.s

# target to build an object file
src/material.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/material.o
.PHONY : src/material.o

# target to preprocess a source file
src/material.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/material.i
.PHONY : src/material.i

# target to generate assembly for a file
src/material.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/material.s
.PHONY : src/material.s

# target to build an object file
src/material_instance.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/material_instance.o
.PHONY : src/material_instance.o

# target to preprocess a source file
src/material_instance.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/material_instance.i
.PHONY : src/material_instance.i

# target to generate assembly for a file
src/material_instance.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/material_instance.s
.PHONY : src/material_instance.s

# target to build an object file
src/mesh.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh.o
.PHONY : src/mesh.o

# target to preprocess a source file
src/mesh.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh.i
.PHONY : src/mesh.i

# target to generate assembly for a file
src/mesh.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh.s
.PHONY : src/mesh.s

# target to build an object file
src/mesh/multiResPlane.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/multiResPlane.o
.PHONY : src/mesh/multiResPlane.o

# target to preprocess a source file
src/mesh/multiResPlane.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/multiResPlane.i
.PHONY : src/mesh/multiResPlane.i

# target to generate assembly for a file
src/mesh/multiResPlane.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/multiResPlane.s
.PHONY : src/mesh/multiResPlane.s

# target to build an object file
src/mesh/primitiveMesh.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/primitiveMesh.o
.PHONY : src/mesh/primitiveMesh.o

# target to preprocess a source file
src/mesh/primitiveMesh.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/primitiveMesh.i
.PHONY : src/mesh/primitiveMesh.i

# target to generate assembly for a file
src/mesh/primitiveMesh.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/primitiveMesh.s
.PHONY : src/mesh/primitiveMesh.s

# target to build an object file
src/mesh/sphereMesh.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/sphereMesh.o
.PHONY : src/mesh/sphereMesh.o

# target to preprocess a source file
src/mesh/sphereMesh.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/sphereMesh.i
.PHONY : src/mesh/sphereMesh.i

# target to generate assembly for a file
src/mesh/sphereMesh.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/sphereMesh.s
.PHONY : src/mesh/sphereMesh.s

# target to build an object file
src/mesh/voxel/hexelMesh.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/voxel/hexelMesh.o
.PHONY : src/mesh/voxel/hexelMesh.o

# target to preprocess a source file
src/mesh/voxel/hexelMesh.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/voxel/hexelMesh.i
.PHONY : src/mesh/voxel/hexelMesh.i

# target to generate assembly for a file
src/mesh/voxel/hexelMesh.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/voxel/hexelMesh.s
.PHONY : src/mesh/voxel/hexelMesh.s

# target to build an object file
src/mesh/voxel/voxelMesh.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/voxel/voxelMesh.o
.PHONY : src/mesh/voxel/voxelMesh.o

# target to preprocess a source file
src/mesh/voxel/voxelMesh.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/voxel/voxelMesh.i
.PHONY : src/mesh/voxel/voxelMesh.i

# target to generate assembly for a file
src/mesh/voxel/voxelMesh.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh/voxel/voxelMesh.s
.PHONY : src/mesh/voxel/voxelMesh.s

# target to build an object file
src/mesh_buffer.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh_buffer.o
.PHONY : src/mesh_buffer.o

# target to preprocess a source file
src/mesh_buffer.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh_buffer.i
.PHONY : src/mesh_buffer.i

# target to generate assembly for a file
src/mesh_buffer.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh_buffer.s
.PHONY : src/mesh_buffer.s

# target to build an object file
src/mesh_builder.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh_builder.o
.PHONY : src/mesh_builder.o

# target to preprocess a source file
src/mesh_builder.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh_builder.i
.PHONY : src/mesh_builder.i

# target to generate assembly for a file
src/mesh_builder.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/mesh_builder.s
.PHONY : src/mesh_builder.s

# target to build an object file
src/model.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/model.o
.PHONY : src/model.o

# target to preprocess a source file
src/model.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/model.i
.PHONY : src/model.i

# target to generate assembly for a file
src/model.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/model.s
.PHONY : src/model.s

# target to build an object file
src/obj.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/obj.o
.PHONY : src/obj.o

# target to preprocess a source file
src/obj.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/obj.i
.PHONY : src/obj.i

# target to generate assembly for a file
src/obj.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/obj.s
.PHONY : src/obj.s

# target to build an object file
src/render_node.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/render_node.o
.PHONY : src/render_node.o

# target to preprocess a source file
src/render_node.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/render_node.i
.PHONY : src/render_node.i

# target to generate assembly for a file
src/render_node.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/render_node.s
.PHONY : src/render_node.s

# target to build an object file
src/renderer.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/renderer.o
.PHONY : src/renderer.o

# target to preprocess a source file
src/renderer.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/renderer.i
.PHONY : src/renderer.i

# target to generate assembly for a file
src/renderer.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/renderer.s
.PHONY : src/renderer.s

# target to build an object file
src/scene.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/scene.o
.PHONY : src/scene.o

# target to preprocess a source file
src/scene.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/scene.i
.PHONY : src/scene.i

# target to generate assembly for a file
src/scene.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/scene.s
.PHONY : src/scene.s

# target to build an object file
src/texture.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/texture.o
.PHONY : src/texture.o

# target to preprocess a source file
src/texture.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/texture.i
.PHONY : src/texture.i

# target to generate assembly for a file
src/texture.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/texture.s
.PHONY : src/texture.s

# target to build an object file
src/texture_data.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/texture_data.o
.PHONY : src/texture_data.o

# target to preprocess a source file
src/texture_data.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/texture_data.i
.PHONY : src/texture_data.i

# target to generate assembly for a file
src/texture_data.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/texture_data.s
.PHONY : src/texture_data.s

# target to build an object file
src/viewport.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/viewport.o
.PHONY : src/viewport.o

# target to preprocess a source file
src/viewport.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/viewport.i
.PHONY : src/viewport.i

# target to generate assembly for a file
src/viewport.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/viewport.s
.PHONY : src/viewport.s

# target to build an object file
src/vrp.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/vrp.o
.PHONY : src/vrp.o

# target to preprocess a source file
src/vrp.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/vrp.i
.PHONY : src/vrp.i

# target to generate assembly for a file
src/vrp.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/vrp.s
.PHONY : src/vrp.s

# target to build an object file
src/window.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/window.o
.PHONY : src/window.o

# target to preprocess a source file
src/window.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/window.i
.PHONY : src/window.i

# target to generate assembly for a file
src/window.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/window.s
.PHONY : src/window.s

# target to build an object file
src/world_material.o:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/world_material.o
.PHONY : src/world_material.o

# target to preprocess a source file
src/world_material.i:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/world_material.i
.PHONY : src/world_material.i

# target to generate assembly for a file
src/world_material.s:
	cd /home/david/shared/Projects/HexWorld && $(MAKE) $(MAKESILENT) -f engine/CMakeFiles/engine.dir/build.make engine/CMakeFiles/engine.dir/src/world_material.s
.PHONY : src/world_material.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... engine"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/debug.o"
	@echo "... src/debug.i"
	@echo "... src/debug.s"
	@echo "... src/directory.o"
	@echo "... src/directory.i"
	@echo "... src/directory.s"
	@echo "... src/engine.o"
	@echo "... src/engine.i"
	@echo "... src/engine.s"
	@echo "... src/engine_component.o"
	@echo "... src/engine_component.i"
	@echo "... src/engine_component.s"
	@echo "... src/framebuffer.o"
	@echo "... src/framebuffer.i"
	@echo "... src/framebuffer.s"
	@echo "... src/gui/debug/gui_debug.o"
	@echo "... src/gui/debug/gui_debug.i"
	@echo "... src/gui/debug/gui_debug.s"
	@echo "... src/gui/fonts.o"
	@echo "... src/gui/fonts.i"
	@echo "... src/gui/fonts.s"
	@echo "... src/gui/gui.o"
	@echo "... src/gui/gui.i"
	@echo "... src/gui/gui.s"
	@echo "... src/gui/gui_ext.o"
	@echo "... src/gui/gui_ext.i"
	@echo "... src/gui/gui_ext.s"
	@echo "... src/io/inotify/inotify_context.o"
	@echo "... src/io/inotify/inotify_context.i"
	@echo "... src/io/inotify/inotify_context.s"
	@echo "... src/io/inotify/inotify_handler.o"
	@echo "... src/io/inotify/inotify_handler.i"
	@echo "... src/io/inotify/inotify_handler.s"
	@echo "... src/io/io.o"
	@echo "... src/io/io.i"
	@echo "... src/io/io.s"
	@echo "... src/io/resource.o"
	@echo "... src/io/resource.i"
	@echo "... src/io/resource.s"
	@echo "... src/light.o"
	@echo "... src/light.i"
	@echo "... src/light.s"
	@echo "... src/load_shader.o"
	@echo "... src/load_shader.i"
	@echo "... src/load_shader.s"
	@echo "... src/material.o"
	@echo "... src/material.i"
	@echo "... src/material.s"
	@echo "... src/material_instance.o"
	@echo "... src/material_instance.i"
	@echo "... src/material_instance.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/mesh/multiResPlane.o"
	@echo "... src/mesh/multiResPlane.i"
	@echo "... src/mesh/multiResPlane.s"
	@echo "... src/mesh/primitiveMesh.o"
	@echo "... src/mesh/primitiveMesh.i"
	@echo "... src/mesh/primitiveMesh.s"
	@echo "... src/mesh/sphereMesh.o"
	@echo "... src/mesh/sphereMesh.i"
	@echo "... src/mesh/sphereMesh.s"
	@echo "... src/mesh/voxel/hexelMesh.o"
	@echo "... src/mesh/voxel/hexelMesh.i"
	@echo "... src/mesh/voxel/hexelMesh.s"
	@echo "... src/mesh/voxel/voxelMesh.o"
	@echo "... src/mesh/voxel/voxelMesh.i"
	@echo "... src/mesh/voxel/voxelMesh.s"
	@echo "... src/mesh_buffer.o"
	@echo "... src/mesh_buffer.i"
	@echo "... src/mesh_buffer.s"
	@echo "... src/mesh_builder.o"
	@echo "... src/mesh_builder.i"
	@echo "... src/mesh_builder.s"
	@echo "... src/model.o"
	@echo "... src/model.i"
	@echo "... src/model.s"
	@echo "... src/obj.o"
	@echo "... src/obj.i"
	@echo "... src/obj.s"
	@echo "... src/render_node.o"
	@echo "... src/render_node.i"
	@echo "... src/render_node.s"
	@echo "... src/renderer.o"
	@echo "... src/renderer.i"
	@echo "... src/renderer.s"
	@echo "... src/scene.o"
	@echo "... src/scene.i"
	@echo "... src/scene.s"
	@echo "... src/texture.o"
	@echo "... src/texture.i"
	@echo "... src/texture.s"
	@echo "... src/texture_data.o"
	@echo "... src/texture_data.i"
	@echo "... src/texture_data.s"
	@echo "... src/viewport.o"
	@echo "... src/viewport.i"
	@echo "... src/viewport.s"
	@echo "... src/vrp.o"
	@echo "... src/vrp.i"
	@echo "... src/vrp.s"
	@echo "... src/window.o"
	@echo "... src/window.i"
	@echo "... src/window.s"
	@echo "... src/world_material.o"
	@echo "... src/world_material.i"
	@echo "... src/world_material.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/david/shared/Projects/HexWorld && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

